[package]
name = "hnd"
description = "Handy CLI of developer and system utilities (password generation and more)"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = "README.md"
keywords = ["cli", "password", "generator", "utilities", "tools"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.6.6", features = ["derive", "color", "error-context", "help", "usage", "suggestions", "unicode"] }
thiserror = { workspace = true }
anyhow = { version = "1.0.104" }
# Local
hnd-password-generator = { path = "../tools/password-generator", version = "0.1.1" }

[package.metadata.release]
pre-release-commit-message = "chore(release): Release {{crate_name}} version {{version}}"